myst-6/ukoly

components/Solution/index.tsx
content/problems/base/index.tsx
content/problems/bio1/index.tsx
pages/bio1.tsx
pages/bio2.tsx
public/assets/code/integerstrings/sol.cpp
public/assets/code/integerstrings/sol.py
public/assets/code/parsinglists/sol.py
public/assets/code/unlock/sol.py
public/assets/code/wordgame/sol.py
solutions/bio1/IntegerStrings/index.tsx
solutions/bio1/ParsingLists/index.tsx
solutions/bio1/Unlock/index.tsx
solutions/bio1/WordGame/index.tsx
solutions/bio1/index.tsx
solutions/bio2/Carve/index.tsx
solutions/util/index.tsx

BIO2024 all questions
BIO2013 Q3

A few BIO1 problems and some typo fixes.

---

content/problems/bio2/index.tsx
public/assets/code/terminalvelocity/sol.cpp
solutions/bio2/TerminalVelocity/index.tsx
solutions/bio2/index.tsx

- updated the problem list to show terminal velocity on the site
- added the editorial for terminal velocity
- added the cpp solution for terminal velocity

Added Terminal Velocity

---

content/problems/base/index.tsx
content/problems/bio1/index.tsx
content/problems/bio2/index.tsx
pages/bio1.tsx
pages/bio2.tsx

Changed it to an array as @myst-6 mentioned

Removed the need for problem keys

---

solutions/bio2/Milk/index.tsx
solutions/bio2/Whisperer/index.tsx

Wanted consistency across the editorials. No need to have these constraints here, this ain't NEAR grind

Removed constraints from whisperer and milk

---

components/Problem/index.tsx
content/problems/bio1/index.tsx

I added a divider into the card because I think it looks good, and I made all the cards a fixed height

Fix card size issue

---

content/problems/bio1/index.tsx
public/assets/code/downpat/sol.cpp
public/assets/code/downpat/sol.py
solutions/bio1/DownPat/index.tsx
solutions/bio1/index.tsx

Added 2021Q1

---

components/Profile/index.tsx
content/people/base/index.tsx
content/people/instances/index.tsx
pages/index.tsx

I also removed the description feature, because it's cumbersome to write all of them and I don't think it adds much.

Add contributors

---

README.md
components/Problemset/FilterMenu/index.tsx
components/Problemset/SearchMenu/index.tsx
components/Problemset/SortMenu/index.tsx
components/Problemset/index.tsx

1. Added a sorting feature. You can sort by year, difficulty, or title in ascending or descending order.
2. Added a searching feature. You can search by title.
3. Changed the filter icon to some tags. Let me know if you like this or the old icon better.

Sorting and Searching

---

public/assets/code/blockchains/sol.py

anyone just blindly accept this please I've literally just added a python solution to 2019q3

Added python solution to 2019q3

---

components/Header/index.tsx
components/Problemset/index.tsx
components/Profile/index.tsx
components/Text/index.tsx
pages/_app.tsx
pages/bio1.tsx
pages/bio2.tsx
pages/index.tsx

I think the website works well in portrait mode now...
That was easier than I thought it'd be, lol
So, since I haven't suffered enough, let me know if the layout should change differently anywhere.
Closes #46 as well.

Responsive layout

---

content/problems/bio1/index.tsx
public/assets/code/juggluging/sol.cpp
public/assets/code/juggluging/sol.py
solutions/bio1/Juggluging/index.tsx
solutions/bio1/PrimeConnections/index.tsx
solutions/bio1/index.tsx

Another goddamn BFS. I've kept this one rather brief, linking to another problem which has a full explanation of BFS for the people who don't know it.

Added 2010 Q3

---

content/problems/bio1/index.tsx
public/assets/code/numberladder/sol.cpp
public/assets/code/numberladder/sol.py
solutions/bio1/NumberLadder/index.tsx
solutions/bio1/index.tsx

Number Ladder

---

components/Problem/index.tsx
components/Problemset/ShowMenu/index.tsx
components/Problemset/index.tsx

I added a way for people to hide the difficulty and/or problem type tags, in case they want to avoid seeing this for problems they are still attempting or haven't attempted yet.

Added Show/Hide Menu

---

content/problems/bio1/index.tsx
public/assets/code/mayancalendar/sol.cpp
public/assets/code/mayancalendar/sol.py
solutions/bio1/MayanCalendar/index.tsx
solutions/bio1/index.tsx

Code was 99% GPT, as was editorial. It's entirely correct but like ughhh

Added 2004Q1

---

components/Problem/index.tsx
content/people/instances/index.tsx

Apparently nobody noticed that the view button was still the colour of the difficulty even when the difficulty tag was hidden. Oops. Fixed now! Let me know if you think a different colour should be used, but I think purple looks good and is difficulty ambiguous.

Hiding Problem Dificulty fix

---

pages/index.tsx

people now sorted based on roles
People names in alphabetical order instead of random
(other opinions are welcome)

separated people based on role

---

content/problems/base/index.tsx
content/problems/bio1/index.tsx
solutions/bio1/Ants/index.tsx
solutions/bio1/EnigmaMachine/index.tsx

Changed difficulties

---

content/problems/bio1/index.tsx
public/assets/code/rules/sol.py
solutions/bio1/Rules/index.tsx
solutions/bio1/index.tsx

Now I am become Death, the destroyer of worlds....

2006 Q2 try not to have a heart attack challenge

---

content/problems/bio1/index.tsx
public/assets/code/ontherighttrack/sol.cpp
public/assets/code/ontherighttrack/sol.py
solutions/bio1/OnTheRightTrack/index.tsx
solutions/bio1/index.tsx

Added On The Right Track Q2 2012

---

content/problems/bio1/index.tsx
public/assets/code/playinggames/sol.cpp
public/assets/code/playinggames/sol.py
solutions/bio1/PlayingGames/index.tsx
solutions/bio1/index.tsx

but also i finally made a python
pls work

r1 00 q3 but better

---

components/Problemset/SortMenu/index.tsx

sorts years backwards (2024 first) by default

reversed sorting

---

content/people/instances/index.tsx

remove my discord

---

components/SCodeBlock/index.tsx

Hopefully a PR of all time?

---

components/SCodeBlock/index.tsx
content/index.tsx
content/tests/base/index.tsx
content/tests/index.tsx
utils/index.tsx
utils/invocation/checkers/base.tsx
utils/invocation/checkers/index.tsx
utils/invocation/checkers/ncmp.tsx
utils/invocation/index.tsx
utils/invocation/invoke.tsx
utils/invocation/useInvoker.tsx
utils/invocation/useRunner.tsx
utils/invocation/useTester.tsx

While you may not be able to review all changes to a high standard, you should at least check that the functionality is the same as before, and that you understand the docs.

Add invocation/testing utility files.

---

public/assets/code/anagrams/sol.cpp
public/assets/code/blockpalindromes/bitsol.cpp
public/assets/code/blockpalindromes/recsol.cpp
public/assets/code/cards/sol.cpp
public/assets/code/distinctprimefactorisation/sol.cpp
public/assets/code/downpat/sol.cpp
public/assets/code/fibonacciletters/sol.cpp
public/assets/code/fractions/sol.cpp
public/assets/code/goldbachconjecture/sol.cpp
public/assets/code/isbn/sol.cpp
public/assets/code/numberladder/sol.cpp
public/assets/code/passwords/sol.cpp
public/assets/code/shirts/sol.cpp

Basically I removed all the Python prompts but totally forgot about the C++ ones...

Removed more prompts

---

components/SCodeBlock/CodeBlock.tsx
components/SCodeBlock/index.tsx
components/SRunner/index.tsx
components/index.tsx
pages/grader.tsx

Made SRunner component
added SRunner to grader, doesn't currently function, need to pass in source code in Monaco editor to SRunner component through codes property

Bio1 judge runner component

---

pages/grader.tsx

added submit tab thing

---

content/people/base/index.tsx
content/people/instances/index.tsx
pages/pctc.tsx

pctc again (macaque changes)

---

content/problems/bio1/index.tsx
content/tests/PalindromicSums.tsx
content/tests/index.tsx
public/assets/code/palindromicsums/sol.cpp
public/assets/code/palindromicsums/sol.py
solutions/bio1/PalindromicSums/index.tsx
solutions/bio1/index.tsx

BIO1 - 2025 q1

---

content/problems/bio1/index.tsx
content/tests/SafeHaven.tsx
content/tests/index.tsx
public/assets/code/safehaven/sol.py
solutions/bio1/SafeHaven/index.tsx
solutions/bio1/index.tsx

BIO1 2025 q2
